#pragma once
#ifndef _ENUMRECIPIENTUSERINPUTEVENT_H_
#define _ENUMRECIPIENTUSERINPUTEVENT_H_

enum EnumInputEvent
{
	NOTHING,
	CLOSE_GAME,
	BUTTON_DOWN_W,
	BUTTON_DOWN_S,
	BUTTON_UP_W,
	BUTTON_UP_S
};

#endif